### PR TITLE
PR for https://github.com/easylist/easylistgermany/issues/119

### PR DESCRIPTION
**Pull request by beerisgood**

### CODE REVIEW

**Comment by Khrin** [comment]
@beerisgood I need an example page to use as reference for such a request.

**Comment by beerisgood** [comment]
> @beerisgood I need an example page to use as reference for such a request.

click on random stream on `https://bs.to/`

**Comment by Khrin** [comment]
Sorry but i don't think this pr can be accepted.

I think also some of the adverts you've seen were delivered by known adservers, which are now blocked in EasyList.

**Comment by beerisgood** [comment]
> Sorry but i don't think this pr can be accepted.
> 
why?

> I think also some of the adverts you've seen were delivered by known adservers, which are now blocked in EasyList.
>
No, none of them are blocked. That's why i create this PR

**Pull request closed without merging**
