### PR TITLE
Additional advertising elements

### PR DESCRIPTION
**Pull request by tibor**

### CODE REVIEW

**Comment by monzta** [comment]
Where can I find these elements?

**Comment by Khrin** [comment]
The same reference link from https://github.com/easylist/easylistgermany/pull/75, I suppose.

**Comment by monzta** [comment]
Cannot find ayn of these IDs on that page.

**Comment by tibor** [comment]
They are on
https://www.t-online.de/nachrichten/panorama/
https://www.t-online.de/sport/
https://www.t-online.de/unterhaltung/
https://www.t-online.de/digital/

**Pull request merged**
