### PR TITLE
Update for changed markup of saechsische.de 

### PR DESCRIPTION
**Pull request by Brummolix**

### CODE REVIEW

**Comment by Brummolix** [comment]
Don't you like the line
`saechsische.de#?#.article-fill`

It removes ads/fillers inside articles, for example inside https://www.saechsische.de/sport/fussball/em-2021/fussball-europameisterschaft-news-em-euro-nationalmannschaft-wembley-schweiz-england-deutschland-5459278.html

**Comment by Khrin** [comment]
I don't think these should be blocked, becuase these doesn't look like "ads" to me.

**Comment by Brummolix** [comment]
How about this one? These are at least ads:
`
saechsische.de#?#.article-fill:-abp-has(> .article-fill__section > span:-abp-contains(Anzeige))
saechsische.de#?#.article-fill:-abp-has(> .article-fill__section > span:-abp-contains(TOP Deals))
`

**Comment by Khrin** [comment]
Where's needed `saechsische.de#?#.article-fill:-abp-has(> .article-fill__section > span:-abp-contains(TOP Deals))`? I couldn't find anywhere on the site.

**Comment by Brummolix** [comment]
The article-fill elements change dynamically. I once saw these top deals.
There are even more variants of it. This was the reason I orginally suggested to block them all.
Sometimes there are also regional ones like "Technische Universität Dresden" (technical university dresden), but in my eyes this is still advertising.

**Pull request closed without merging**
