### PR TITLE
A: https://www.welt.de/wirtschaft/article196683317/I.html

### PR DESCRIPTION
**Pull request by smed79**
https://forums.lanik.us/viewtopic.php?p=148700#p148700

### CODE REVIEW

**Comment by monzta** [comment]
What do the filters for gamester.de remove?

**Comment by smed79** [comment]
https://i.vgy.me/ld1qo9.png

**Comment by monzta** [comment]
That's welt.de but I meant gamestar.de

**Comment by smed79** [comment]
Sorry ... there is already a link for details https://i.vgy.me/Y5qiRq.jpg

- https://i.vgy.me/4YTVk0.jpg
- https://forums.lanik.us/viewtopic.php?p=148721#p148721

**Pull request merged**
